Repository Xerip97/PancakeSwap, pull requests merged in 2022-04, with the labels that each got.

#53 Fabio 51
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/earn-undernavbar-div/earn-undernavbar-div.component.css
  src/app/core/earn-undernavbar-div/earn-undernavbar-div.component.html
  src/app/core/earn-undernavbar-div/earn-undernavbar-div.component.spec.ts
  src/app/core/earn-undernavbar-div/earn-undernavbar-div.component.ts
  src/app/core/layout/navbar/navbar.component.css
  src/app/core/layout/navbar/navbar.component.html
  src/app/models/Pool.ts
  src/app/pages/farms-container/farms-container.component.html
  src/app/pages/pools-container/bounty-info/bounty-info.component.css
  src/app/pages/pools-container/bounty-info/bounty-info.component.html
  src/app/pages/pools-container/bounty-info/bounty-info.component.spec.ts
  src/app/pages/pools-container/bounty-info/bounty-info.component.ts
  src/app/pages/pools-container/pools-container.component.css
  src/app/pages/pools-container/pools-container.component.html
  src/app/pages/pools-container/pools-container.component.spec.ts
  src/app/pages/pools-container/pools-container.component.ts
  src/mock/poolsMock.ts
Labels: enhancement, good first issue

#60 Kat 49
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/layout/filter/filter.component.css
  src/app/core/layout/filter/filter.component.html
  src/app/core/layout/filter/filter.component.spec.ts
  src/app/core/layout/filter/filter.component.ts
  src/app/core/layout/footer/footer.component.css
  src/app/designsystem/buttons/btn-double/btn-double.component.ts
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.css
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.html
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.ts
  src/app/designsystem/forms-container/form-slider/form-slider.component.css
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.css
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.html
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.ts
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.css
  src/app/models/Farms.ts
  src/app/pages/farms-container/farms-cards/farms-cards.component.css
  src/app/pages/farms-container/farms-cards/farms-cards.component.html
  src/app/pages/farms-container/farms-cards/farms-cards.component.spec.ts
  src/app/pages/farms-container/farms-cards/farms-cards.component.ts
  src/app/pages/farms-container/farms-container.component.css
  src/app/pages/farms-container/farms-container.component.html
  src/app/pages/farms-container/farms-container.component.ts
  src/app/pages/farms-container/farms-header/farms-header.component.css
  src/app/pages/farms-container/farms-header/farms-header.component.html
  src/app/pages/farms-container/farms-header/farms-header.component.spec.ts
  src/app/pages/farms-container/farms-header/farms-header.component.ts
  src/app/pages/farms-container/farms-table/farms-table.component.css
  src/app/pages/farms-container/farms-table/farms-table.component.html
  src/app/pages/farms-container/farms-table/farms-table.component.spec.ts
  src/app/pages/farms-container/farms-table/farms-table.component.ts
  src/app/pages/test/test.component.html
  src/app/pages/test/test.component.ts
  src/app/shared/services/buttons/btn-double/btn-double.service.spec.ts
  src/app/shared/services/buttons/btn-double/btn-double.service.ts
  src/app/shared/services/filter-view/filter-view.service.spec.ts
  src/app/shared/services/filter-view/filter-view.service.ts
  src/app/shared/services/forms/dropdown/dropdown.service.ts
  src/app/shared/services/forms/search-text/search-text.service.ts
  src/mock/data_1.ts
  src/mock/farmsDropDown.ts
  src/mock/farmsMock.ts
  src/polyfills.ts
  src/styles.css
Labels: good first issue

#61 assignment 48: fix popoverClass and card cake
  package-lock.json
  src/app/pages/farms-container/farms-cards/farms-cards.component.css
  src/app/pages/farms-container/farms-cards/farms-cards.component.html
  src/app/pages/farms-container/farms-cards/farms-cards.component.ts
  src/app/pages/farms-container/farms-container.component.css
  src/app/pages/farms-container/farms-container.component.html
  src/app/pages/farms-container/farms-container.component.ts
  src/app/pages/farms-container/farms-table/farms-table.component.css
  src/app/pages/farms-container/farms-table/farms-table.component.html
  src/styles.css
Labels: good first issue

#65 Kat 62
  src/app/app.module.ts
  src/app/pages/home-container/cake-container/cake-container.component.css
  src/app/pages/home-container/home-container.component.html
  src/app/pages/home-container/home-earn-container/home-earn-animation/home-earn-animation.component.css
  src/app/pages/home-container/home-earn-container/home-earn-animation/home-earn-animation.component.html
  src/app/pages/home-container/home-earn-container/home-earn-animation/home-earn-animation.component.spec.ts
  src/app/pages/home-container/home-earn-container/home-earn-animation/home-earn-animation.component.ts
  src/app/pages/home-container/home-earn-container/home-earn-container.component.css
  src/app/pages/home-container/home-earn-container/home-earn-container.component.html
  src/app/pages/home-container/home-earn-container/home-earn-container.component.spec.ts
  src/app/pages/home-container/home-earn-container/home-earn-container.component.ts
  src/app/pages/home-container/home-earn-container/home-earn-desc/home-earn-desc.component.css
  src/app/pages/home-container/home-earn-container/home-earn-desc/home-earn-desc.component.html
  src/app/pages/home-container/home-earn-container/home-earn-desc/home-earn-desc.component.spec.ts
  src/app/pages/home-container/home-earn-container/home-earn-desc/home-earn-desc.component.ts
  src/app/pages/home-container/home-earn-container/home-earn-table/home-earn-table.component.css
  src/app/pages/home-container/home-earn-container/home-earn-table/home-earn-table.component.html
  src/app/pages/home-container/home-earn-container/home-earn-table/home-earn-table.component.spec.ts
  src/app/pages/home-container/home-earn-container/home-earn-table/home-earn-table.component.ts
  src/app/pages/home-container/home-win-container/home-lottery-animation/home-lottery-animation.component.css
  src/app/pages/home-container/home-win-container/home-lottery-animation/home-lottery-animation.component.html
  src/app/pages/home-container/home-win-container/home-lottery-animation/home-lottery-animation.component.spec.ts
  src/app/pages/home-container/home-win-container/home-lottery-animation/home-lottery-animation.component.ts
  src/app/pages/home-container/home-win-container/home-prediction-animation/home-prediction-animation.component.css
  src/app/pages/home-container/home-win-container/home-prediction-animation/home-prediction-animation.component.html
  src/app/pages/home-container/home-win-container/home-prediction-animation/home-prediction-animation.component.spec.ts
  src/app/pages/home-container/home-win-container/home-prediction-animation/home-prediction-animation.component.ts
  src/app/pages/home-container/home-win-container/home-win-container.component.css
  src/app/pages/home-container/home-win-container/home-win-container.component.html
  src/app/pages/home-container/home-win-container/home-win-container.component.spec.ts
  src/app/pages/home-container/home-win-container/home-win-container.component.ts
  src/app/pages/home-container/home-win-container/home-win-lottery/home-win-lottery.component.css
  src/app/pages/home-container/home-win-container/home-win-lottery/home-win-lottery.component.html
  src/app/pages/home-container/home-win-container/home-win-lottery/home-win-lottery.component.spec.ts
  src/app/pages/home-container/home-win-container/home-win-lottery/home-win-lottery.component.ts
  src/app/pages/home-container/home-win-container/home-win-prediction/home-win-prediction.component.css
  src/app/pages/home-container/home-win-container/home-win-prediction/home-win-prediction.component.html
  src/app/pages/home-container/home-win-container/home-win-prediction/home-win-prediction.component.spec.ts
  src/app/pages/home-container/home-win-container/home-win-prediction/home-win-prediction.component.ts
  src/app/pages/leaderboard-container/leaderboard-container.component.css
  src/app/pages/leaderboard-container/teams/teams.component.css
  src/app/pages/leaderboard-container/teams/teams.component.html
  src/app/shared/style/cards-home.css
  src/styles.css
Labels: enhancement

#66 Marco 53 HomePage components Trade-static
  src/app/app.module.ts
  src/app/pages/home-container/home-container.component.html
  src/app/pages/home-container/home-people-statistic-container/home-people-statistic-container.component.css
  src/app/pages/home-container/home-people-statistic-container/home-people-statistic-container.component.html
  src/app/pages/home-container/home-people-statistic-container/home-people-statistic-container.component.spec.ts
  src/app/pages/home-container/home-people-statistic-container/home-people-statistic-container.component.ts
  src/app/pages/home-container/home-trade-container/home-trade-container.component.css
  src/app/pages/home-container/home-trade-container/home-trade-container.component.html
  src/app/pages/home-container/home-trade-container/home-trade-container.component.spec.ts
  src/app/pages/home-container/home-trade-container/home-trade-container.component.ts
  src/assets/svg/BNB.png
  src/assets/svg/BNB@2x.webp
  src/assets/svg/BTC.png
  src/assets/svg/BTC@2x.webp
  src/assets/svg/CAKE.png
  src/assets/svg/Home_violet_string.svg
  src/assets/svg/bunny_icon_violet.svg
  src/assets/svg/coin@2x.webp
  src/assets/svg/folder.png
  src/assets/svg/icon_community_violet.svg
  src/assets/svg/icon_graph_homepage_pink.svg
  src/assets/svg/pie.png
  src/assets/svg/stonks.png
  src/assets/svg/trades_home.svg
  src/styles.css
Labels: good first issue

#68 Fabio 51
  src/app/app.module.ts
  src/app/core/layout/footer/footer.component.css
  src/app/core/layout/footer/footer.component.html
  src/app/core/layout/footer/footer.component.ts
  src/app/models/Pool.ts
  src/app/pages/farms-container/farms-cards/farms-cards.component.html
  src/app/pages/farms-container/farms-cards/farms-cards.component.ts
  src/app/pages/pools-container/bounty-info/bounty-info.component.html
  src/app/pages/pools-container/pools-cards/pools-cards.component.css
  src/app/pages/pools-container/pools-cards/pools-cards.component.html
  src/app/pages/pools-container/pools-cards/pools-cards.component.spec.ts
  src/app/pages/pools-container/pools-cards/pools-cards.component.ts
  src/app/pages/pools-container/pools-container.component.css
  src/app/pages/pools-container/pools-container.component.html
  src/app/pages/pools-container/pools-container.component.ts
  src/app/pages/pools-container/pools-table/pools-table.component.css
  src/app/pages/pools-container/pools-table/pools-table.component.html
  src/app/pages/pools-container/pools-table/pools-table.component.spec.ts
  src/app/pages/pools-container/pools-table/pools-table.component.ts
  src/app/shared/services/forms/search-text/search-text.service.ts
  src/assets/svg/double_rotate_arrow .svg
  src/assets/svg/rotate_arrow.svg
  src/assets/svg/timer.svg
  src/mock/poolsDropDown.ts
  src/mock/poolsMock.ts
Labels: enhancement

#67 Marco 51 liquidity full and homepage fix img
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core/layout/navbar/navbar.component.html
  src/app/core/setting/setting.component.css
  src/app/core/setting/setting.component.html
  src/app/core/setting/setting.component.spec.ts
  src/app/core/setting/setting.component.ts
  src/app/core/trade-undernavbar-div/trade-undernavbar-div.component.css
  src/app/core/trade-undernavbar-div/trade-undernavbar-div.component.html
  src/app/core/trade-undernavbar-div/trade-undernavbar-div.component.spec.ts
  src/app/core/trade-undernavbar-div/trade-undernavbar-div.component.ts
  src/app/core/warning-banner/warning-banner.component.css
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.css
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.css
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.html
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.ts
  src/app/pages/design-system/design-system.component.css
  src/app/pages/design-system/design-system.component.html
  src/app/pages/farms-container/farms-cards/farms-cards.component.css
  src/app/pages/farms-container/farms-cards/farms-cards.component.html
  src/app/pages/farms-container/farms-cards/farms-cards.component.ts
  src/app/pages/farms-container/farms-container.component.css
  src/app/pages/home-container/home-trade-container/trade-anim/trade-anim.component.css
  src/app/pages/liquidity-container/liquidity-container.component.css
  src/app/pages/liquidity-container/liquidity-container.component.html
  src/app/pages/liquidity-container/liquidity-container.component.spec.ts
  src/app/pages/liquidity-container/liquidity-container.component.ts
  src/app/pages/test/test.component.ts
  src/app/shared/style/btns.css
  src/assets/svg/graph_popup_violet.svg
Labels: good first issue
