Repository Xerip97/PancakeSwap, pull requests merged in 2022-03, with the labels that each got.

#33 Fabio 20
  src/app/designsystem/navbar/navbar/navbar.component.css
  src/app/designsystem/navbar/navbar/navbar.component.html
Labels: enhancement

#34 Fabio 20
  src/app/designsystem/navbar/navbar/navbar.component.css
  src/app/designsystem/navbar/navbar/navbar.component.html
Labels: enhancement

#35 Fabio 20
  src/app/designsystem/navbar/navbar/navbar.component.css
  src/app/designsystem/navbar/navbar/navbar.component.html
  src/app/designsystem/navbar/navbar/navbar.component.ts
Labels: enhancement

#36 Kat13
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.css
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.html
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.spec.ts
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.ts
  src/app/designsystem/forms-container/form-poll/form-poll.component.css
  src/app/designsystem/forms-container/form-poll/form-poll.component.html
  src/app/designsystem/forms-container/form-poll/form-poll.component.spec.ts
  src/app/designsystem/forms-container/form-poll/form-poll.component.ts
  src/app/designsystem/forms-container/form-slider/form-slider.component.css
  src/app/designsystem/forms-container/form-slider/form-slider.component.html
  src/app/designsystem/forms-container/form-slider/form-slider.component.spec.ts
  src/app/designsystem/forms-container/form-slider/form-slider.component.ts
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.css
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.html
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.spec.ts
  src/app/designsystem/forms-container/form-text-search/form-text-search.component.ts
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.css
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.html
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.spec.ts
  src/app/designsystem/forms-container/form-text-trade/form-text-trade.component.ts
  src/app/designsystem/forms-container/forms-container.component.css
  src/app/designsystem/forms-container/forms-container.component.html
  src/app/designsystem/forms-container/forms-container.component.spec.ts
  src/app/designsystem/forms-container/forms-container.component.ts
  src/styles.css
Labels: good first issue

#45 Marco 3
  package-lock.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/btn-tris/btn-tris.component.css
  src/app/btn-tris/btn-tris.component.html
  src/app/btn-tris/btn-tris.component.spec.ts
  src/app/btn-tris/btn-tris.component.ts
  src/app/shared/style/btns.css
  src/index.html
Labels: documentation

#47 Fabio 44
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/models/Team.ts
  src/app/pages/leaderboard-container/leaderboard-container.component.html
  src/app/pages/leaderboard-container/leaderboard-container.component.ts
  src/app/pages/leaderboard-container/team-container/team-container.component.css
  src/app/pages/leaderboard-container/team-container/team-container.component.html
  src/app/pages/leaderboard-container/team-container/team-container.component.spec.ts
  src/app/pages/leaderboard-container/team-container/team-container.component.ts
  src/app/pages/leaderboard-container/team-container/team1/team1.component.css
  src/app/pages/leaderboard-container/team-container/team1/team1.component.html
  src/app/pages/leaderboard-container/team-container/team1/team1.component.spec.ts
  src/app/pages/leaderboard-container/team-container/team1/team1.component.ts
  src/app/pages/leaderboard-container/team-container/team2/team2.component.css
  src/app/pages/leaderboard-container/team-container/team2/team2.component.html
  src/app/pages/leaderboard-container/team-container/team2/team2.component.spec.ts
  src/app/pages/leaderboard-container/team-container/team2/team2.component.ts
  src/app/pages/leaderboard-container/team-container/team3/team3.component.css
  src/app/pages/leaderboard-container/team-container/team3/team3.component.html
  src/app/pages/leaderboard-container/team-container/team3/team3.component.spec.ts
  src/app/pages/leaderboard-container/team-container/team3/team3.component.ts
  src/app/pages/leaderboard-container/teams/teams.component.html
  src/app/pages/leaderboard-container/teams/teams.component.ts
  src/app/shared/services/pages/leaderboard-teams.service.ts
  src/assets/svg/coming-soon-grey.svg
  src/assets/svg/people-blue.svg
  src/assets/svg/people.svg
  src/assets/svg/trophy-grey.svg
Labels: good first issue

#52 Kat 29
  src/app/app.module.ts
  src/app/designsystem/buttons/btn-double/btn-double.component.css
  src/app/designsystem/buttons/btn-double/btn-double.component.html
  src/app/designsystem/buttons/btn-double/btn-double.component.spec.ts
  src/app/designsystem/buttons/btn-double/btn-double.component.ts
  src/app/designsystem/buttons/btn-tris/btn-tris.component.css
  src/app/designsystem/buttons/btn-tris/btn-tris.component.html
  src/app/designsystem/buttons/btn-tris/btn-tris.component.spec.ts
  src/app/designsystem/buttons/btn-tris/btn-tris.component.ts
  src/app/designsystem/forms-container/form-dropdown/form-dropdown.component.ts
  src/app/pages/test/test.component.html
  src/app/pages/test/test.component.ts
  src/app/shared/services/buttons/btn-double.service.spec.ts
  src/app/shared/services/buttons/btn-double.service.ts
  src/mock/data_5.ts
Labels: bug, good first issue
